snaike/config/routes.rb
Websnaike::Application.routes.draw do
  resources :snaikes

 root :to => 'snaikes#home'

end

snaike/app/models/snaike.rb
class Snaike < ActiveRecord::Base
  attr_accessible :ai, :colour, :name

  validates :name,  :presence => true,
                    :length => { :minimum => 1 },
                    :uniqueness => true
end

snaike/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

snaike/app/controllers/snaikes_controller.rb
class SnaikesController < ApplicationController
  # GET /snaikes
  # GET /snaikes.json
  def home
    @snaikes = Snaike.all
    @snaike = Snaike.new
  end

  # GET /snaikes
  # GET /snaikes.json
  def index
    @snaikes = Snaike.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snaikes }
    end
  end

  # GET /snaikes/1
  # GET /snaikes/1.json
  def show
    @snaike = Snaike.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snaike }
    end
  end

  # GET /snaikes/new
  # GET /snaikes/new.json
  def new
    @snaike = Snaike.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snaike }
    end
  end

  # GET /snaikes/1/edit
  def edit
    @snaike = Snaike.find(params[:id])
  end

  # POST /snaikes
  # POST /snaikes.json
  def create
    @snaike = Snaike.new(params[:snaike])

    respond_to do |format|
      if @snaike.save
        format.html { redirect_to @snaike, notice: 'Snaike was successfully created.' }
        format.json { render json: @snaike, status: :created, location: @snaike }
      else
        format.html { render action: "new" }
        format.json { render json: @snaike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snaikes/1
  # PUT /snaikes/1.json
  def update
    create
  end

end

snaike/app/helpers/application_helper.rb
module ApplicationHelper
end

snaike/app/helpers/snaikes_helper.rb
module SnaikesHelper
end

snaike/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snaike!</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

snaike/app/views/snaikes/_form.html.erb
<%= form_for(@snaike) do |f| %>
  <% if @snaike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snaike.errors.count, "error") %> prohibited this snaike from being saved:</h2>

      <ul>
      <% @snaike.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="container">
    <div class="row">
      <div class="span9">
        <h2>Create your own snaike</h2>
        <form class="form-inline">
          <pre>
  //Represents a snake on an n*m grid, the top left coordinate being [0,0]
  var MySnaike = function (<span id="gridWidth">gridWidth</span>, <span id="gridHeight">gridHeight</span>,<span id="nextPosition">nextPosition</span>, <span id="turnDirection">turnDirection</span>,<span id="snakeAtPosition">snakeAtPosition</span>) {
    var _this = {};
    //Name used for scoreboard
    _this.name = "<%= f.text_field :name, :required=>"required" %>";
    //CSS body colour
    _this.colour = "<%= f.text_field :colour %>";
    //Strategy
    //Returns an number indicating if the snake should turn before it moves forward this move
    //Negative numbers turn left, 0 moves forward without turning, positive numbers turn right
    //E.g. -1, 0 or 1
    _this.think = function (<span id="snakePositions">snakePositions</span>, <span id="myIndex">myIndex</span>, <span id="myDirection">myDirection</span>) {
      <%= f.text_area :ai, :class=>"ai_input" %>
    };
    return _this;
  };
          </pre>
          <button class="btn btn-primary" id="test_ai">Test inline</button>
          <button class="btn btn-primary">Submit snaike</button>
        </form>
      </div>
    </div>
  </div>
  <script>
    $('#gridWidth').popover({
      title: "gridWidth:",
      content: "A positive integer representing the total number of grid positions along the horizontal axis.",
      trigger: "hover",
      placement:"top"
    });
    $('#gridHeight').popover({
      title: "gridHeight:",
      content: "A positive integer representing the total number of grid positions along the vertical axis.",
      trigger: "hover",
      placement:"top"
    });
    $('#nextPosition').popover({
      title: "nextPosition:",
      content: "function(dir, turn) ... Takes a current direction (0-3) and a possible turn (<0 or >0), returning the direction after turning (0-3).",
      trigger: "hover",
      placement:"top"
    });
    $('#turnDirection').popover({
      title: "turnDirection:",
      content: "function(pos, dir) ... Takes a current position ([x,y]) and a direction (0-3) and returns the position resulted from moving 1 square in that direction.",
      trigger: "hover",
      placement:"top"
    });
    $('#snakeAtPosition').popover({
      title: "snakeAtPosition:",
      content: "function(pos) ... Tests if there's a snake at the given position ([x,y]), returning the index into snakePositions of the occupying snake, or -1 if empty.",
      trigger: "hover",
      placement:"top"
    });
    $('#snakePositions').popover({
      title: "snakePositions:",
      content: "An array of all snakes current positions e.g. [[[2,0],[2,1]][[13,12],[13,13]]]. The last coordinate in each snake's position array is its head.",
      trigger: "hover",
      placement:"top"
    });
    $('#myIndex').popover({
      title: "myIndex:",
      content: "The index of your snake in the snakePositions array.",
      trigger: "hover",
      placement:"top"
    });
    $('#myDirection').popover({
      title: "myDirection:",
      content: "A number representing the current direction your next move will be made in if you return 0. 0 - North, 1 - East, 2 - South, 3 - West",
      trigger: "hover",
      placement:"top"
    });
  </script>
  <% end %>

snaike/app/views/snaikes/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @snaike %> |
<%= link_to 'Back', snaikes_path %>

snaike/app/views/snaikes/home.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>SnAIke!</title>
</head>
<body>
<div class="content">

	<div class="centered">
		<h1>Snaike!</h1>

		<div>
			<div>
				<canvas id="game_canvas" width="800" height="400">
				</canvas>
			</div>
		</div>
		<button type="button" class="btn btn-primary" id="reset">Restart</button>
	</div>
	<div>
		<% @snaike = Snaike.new %>
		<%= render 'form' %>
	</div>
	<div class="snaike_select pad_bottom">
		<h2>Select the snaikes to battle</h2>
		<table>
		  <tr>
		    <th></th>
		    <th>Name</th>
		    <th>Colour</th>
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>

		<% @snaikes.each do |snaike| %>
		  <tr id="snaikeId_<%= snaike.id %>">
		    <td><input name="select" type="checkbox" /><pre id="snaikeAI_<%= snaike.id %>" class="hidden_ai"><%= snaike.ai %></pre></td>
		    <td id="snaikeName_<%= snaike.id %>"><%= snaike.name %></td>
		    <td id="snaikeColour_<%= snaike.id %>" style="background-color:<%= snaike.colour %>"><%= snaike.colour %></td>
		    <td><%= link_to 'Show', snaike %></td>
		    <td><%= link_to 'Edit', edit_snaike_path(snaike) %></td>
		  </tr>
		<% end %>
		</table>

	</div>
		<button type="button" class="btn btn-primary" id="battle_selected">Battle selected snaikes</button>
		<br />
		<br />
</div>
<script type="text/javascript">
(function(){
	var f;
	if (typeof window.onload === "function") {
		f = window.onload;
	}
	window.onload = function() {
		if (typeof f === "function") {
			f.apply(arguments);
		}
		if (typeof initSnaikeGame === "function") {
			initSnaikeGame();
		}
	}
})();
</script>
</body>
</html>

snaike/app/views/snaikes/index.html.erb
<h1>Listing snaikes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Colour</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @snaikes.each do |snaike| %>
  <tr>
    <td><%= snaike.name %></td>
    <td style="background-color:<%= snaike.colour %>"><%= snaike.colour %></td>
    <td><%= link_to 'Show', snaike %></td>
    <td><%= link_to 'Edit', edit_snaike_path(snaike) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Snaike', new_snaike_path %>

snaike/app/views/snaikes/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', snaikes_path %>

snaike/app/views/snaikes/old_form.html.erb
<%= form_for(@snaike) do |f| %>
  <% if @snaike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snaike.errors.count, "error") %> prohibited this snaike from being saved:</h2>

      <ul>
      <% @snaike.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ai %><br />
    <%= f.text_area :ai %>
  </div>
  <div class="field">
    <%= f.label :colour %><br />
    <%= f.text_field :colour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

snaike/app/views/snaikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @snaike.name %>
</p>

<p>
  <b>Ai:</b>
  <pre><%= @snaike.ai %></pre>
</p>

<p>
  <b>Colour:</b>
  <%= @snaike.colour %>
  <% 5.times do %>
  	<span class="colour_block" style="background-color:<%= @snaike.colour %>"></span>
  <% end %>
</p>


<%= link_to 'Edit', edit_snaike_path(@snaike) %> |
<%= link_to 'Back', snaikes_path %>